# Defines parameters for deployment and management of the app pod>container

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aviale
  labels:
    app: aviale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aviale
  template:
    metadata:
      labels:
        app: aviale
    spec:
      containers:
      - name: aviale
        image: rahimhussain95/aviale:a32d1d25f0b0ec58eecdbfd4516afea2be30d084
        env:
        - name: AERO_API_KEY
          value: "0cdFDvAgREHNAXtyeJiZcJeeADYMSKcr"  
        - name: AERO_API_SOURCE
          value: "https://aeroapi.flightaware.com/aeroapi"  
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
