# Securely exposes Aviale K8s pod internally to accept connection from local cluster

apiVersion: v1
kind: Service
metadata:
  name: aviale-service
  labels:
    app: aviale
spec:
  selector:
    app: aviale
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
