# Allows for centralized ArgoCD app management through a consolidated "app" that routes to ArgoCD apps within the pipeline

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rahimhussain95/kubernetes-repo.git
    targetRevision: main
    path: argocd 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
