apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aviale
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rahimhussain95/kubernetes-repo.git
    targetRevision: main
    path: apps/aviale  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
